<a href="https://colab.research.google.com/github/solomon7-data/Employee-/blob/main/Advanced_Data_Cleaning_for_real_world_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
DATA = pd.read_csv(r"https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv")

# What to clean from this data set by observing the data
- [x] Get ride of bullet in used names
- [x] Get ride of columns not usefull
- [x] split 'height'/'wight' and convert them to integers
- [x] parse out date from 'Born' and 'Died' column
- [x] parse out city, country and region from 'Born'
- [x] calculate age at death

In [ ]:
df = DATA.copy()

In [ ]:
df.head(1)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [ ]:

# does all the used name contains that bullet point in between
len(df)

145500

In [ ]:
# so all the names in the df contains "•"
len(df[df['Used name'].str.contains("•")])

145500

In [ ]:
# remove that character from the used name
df['name'] = df['Used name'].str.replace("•"," ")

In [ ]:
len(df[~df.Measurements.isna()])

107833

In [ ]:
# make sure all the measurment columns contain "/" unless we have to use another apporach to split measurements wight and height
df[~df["Measurements"].str.contains("/",na=False) & df["Measurements"].notna()]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard

In [ ]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ",'_')
df.head(5)

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,nick/petnames,title(s),other_names,nationality,original_name,name_order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [ ]:
# we will creat a toy data frame to check our codes on small scale and then to ther real project
toy = pd.DataFrame(['100 cm','125 cm/45 kg', '35 cm/25 kg','100 kg'], columns = ['measurements'])
toy

   measurements
0        100 cm
1  125 cm/45 kg
2   35 cm/25 kg
3        100 kg

In [ ]:
toy['height'] = toy['measurements'].str.extract(r"(\d+\s*cm)")
toy['weight'] = toy['measurements'].str.extract(r"(\d+\s*kg)")
toy

   measurements  height  weight
0        100 cm  100 cm     NaN
1  125 cm/45 kg  125 cm   45 kg
2   35 cm/25 kg   35 cm   25 kg
3        100 kg     NaN  100 kg

In [ ]:
# we applied the code what we have tested on the small scale data
df['height_cm'] = df.measurements.str.extract(r"(\d+\s*cm)")
df['weight_kg'] = df.measurements.str.extract(r"(\d+\s*kg)")
df['height_cm'] = df['height_cm'].str.replace("cm","").astype('Int64')
df['weight_kg'] = df['weight_kg'].str.replace("kg","").astype('Int64')
df.head(2)

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,nick/petnames,title(s),other_names,nationality,original_name,name_order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,<NA>,<NA>
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183,76

In [ ]:
# check again for changes that is made and spliting the measurements found to be good with the extract method
df[~df["measurements"].str.contains("/",na=False) & df["measurements"].notna()].head()

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,nick/petnames,title(s),other_names,nationality,original_name,name_order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178,<NA>
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191,<NA>
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,<NA>,120
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161,<NA>
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161,<NA>

In [ ]:
# who is the tallest athlet
df.sort_values('height_cm',ascending=False).head(1)

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,nick/petnames,title(s),other_names,nationality,original_name,name_order,name,height_cm,weight_kg
89070,Competed in Olympic Games • Other,Male,Yao•Ming,Yao•Ming,"12 September 1980 in Xuhui District, Shanghai ...",NaN,People's Republic of China,89782,226 cm / 141 kg,"Shanghai Sharks, Shanghai (CHN) / Houston Rock...",NaN,NaN,NaN,NaN,姚•明,Oriental,Yao Ming,226,141

In [ ]:
# extract the date formate from 'born' column
pattern = r'(\d+ \w+ \d{4})'
pattern2 = r'(\d{1,2} \w+ \d{4}|\d{4})'
df['born_date'] = df['born'].str.extract(r'(\d{1,2} \w+ \d{4}|\d{4})')
df['date_died'] = df['died'].str.extract(r'(\d{1,2} \w+ \d{4}|\d{4})')

In [ ]:
# change both the new columns born and died date to datetime data type
df['born_date'] = pd.to_datetime(df['born_date'],format="mixed")
df['date_died'] = pd.to_datetime(df['date_died'],format="mixed")

In [ ]:
# here we realize that the born column is not uniform as we expected and the above method will not be usefull
df[~df['born'].str.match(pattern,na=False) & df['born'].notna()]

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,...,title(s),other_names,nationality,original_name,name_order,name,height_cm,weight_kg,born_date,date_died
91,Competed in Olympic Games,Male,Lionel Hunter•Escombe,Lionel•Escombe,"1876 in Natal, KwaZulu-Natal (RSA)","15 October 1914 in Brentford, England (GBR)",Great Britain,92,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Lionel Escombe,<NA>,<NA>,1876-01-01,1914-10-15
179,Competed in Olympic Games,Male,Pantelis•Papadopoulos,Pantelis•Papadopoulos,1902,1987,Greece,180,NaN,Lawn Tennis Athens,...,NaN,NaN,NaN,Παντελής•Παπαδόπουλος,NaN,Pantelis Papadopoulos,<NA>,<NA>,1902-01-01,1987-01-01
552,Competed in Olympic Games,Female,Emily Jane•Rushton (Ormrod-),Emily•Rushton,"1850 in Halliwell, England (GBR)","30 June 1939 in Barnacre-with-Bonds, Garstang,...",Great Britain,554,NaN,"Barnacre Archers, Barnacre-with-Bonds, Garstan...",...,NaN,NaN,NaN,NaN,NaN,Emily Rushton,<NA>,<NA>,1850-01-01,1939-06-30
561,Competed in Olympic Games,Female,Hilda•Williams,Hilda•Williams,"1876 in Marton, England (GBR)","10 July 1922 in Surbiton, England (GBR)",Great Britain,563,NaN,"Mid Surrey Archery Club, Surbiton (GBR)",...,NaN,NaN,NaN,NaN,NaN,Hilda Williams,<NA>,<NA>,1876-01-01,1922-07-10
667,Competed in Olympic Games,Female,Marie•Jones,Marie•Jones,1896,NaN,Belgium,670,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Marie Jones,<NA>,<NA>,1896-01-01,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,Competed in Olympic Games,Male,"J. Edward ""Eddie""•Heron",Eddie•Heron,"1910 in Dublin, Dublin (IRL)","23 April 1985 in Dublin, Dublin (IRL)",Ireland,120008,NaN,"Sandycove Swimming Club, Sandycove (IRL)",...,NaN,NaN,NaN,NaN,NaN,Eddie Heron,<NA>,<NA>,1910-01-01,1985-04-23
118344,Competed in Olympic Games,Female,Lilo•Mund Borgs,Lilo•Mund,"1939 in Santiago, Santiago Metropolitan (CHI)",NaN,Chile,120048,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Lilo Mund,<NA>,<NA>,1939-01-01,NaT
124915,Competed in Olympic Games,Male,"William•Taylor, Jr.",William•Taylor,"1870 in Hoxton, England (GBR)",NaN,Great Britain,127258,NaN,"Essex Beagles, Barking (GBR)",...,NaN,NaN,NaN,NaN,NaN,William Taylor,<NA>,<NA>,1870-01-01,NaT
126482,Competed in Olympic Games,Male,Cornelius•von Lubowiecki,Cornelius•von Lubowiecki,1876,NaN,Austria,128837,NaN,"Wiener AC, Wien (AUT)",...,NaN,NaN,NaN,NaN,NaN,Cornelius von Lubowiecki,<NA>,<NA>,1876-01-01,NaT
135276,Competed in Olympic Games,Male,"Louis•Dufour, Sr.","Louis•Dufour, Sr.","1873 in Les Avants, Vaud (SUI)",12 April 1944,Switzerland,138439,NaN,"Les Avants HC, Les Avants (SUI)",...,NaN,NaN,NaN,NaN,NaN,"Louis Dufour, Sr.",<NA>,<NA>,1873-01-01,1944-04-12

In [ ]:
# check for the above code if it works correctly by filttering the data
df[~df['born'].str.match(pattern,na=False) & df['born'].notna() & ~df['born'].str.match(pattern2,na=False)]

,roles,sex,full_name,used_name,born,died,noc,athlete_id,measurements,affiliations,...,title(s),other_names,nationality,original_name,name_order,name,height_cm,weight_kg,born_date,date_died
1251,Competed in Olympic Games,Male,Eduardo•Cornejo Díaz,Eduardo•Cornejo,(c. 1929),"23 November 1998 in Santiago, Santiago Metropo...",Chile,1258,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Eduardo Cornejo,<NA>,<NA>,1929-01-01,1998-11-23
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel•Videla,(circa 1920),NaN,Chile,1284,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Manuel Videla,<NA>,<NA>,1920-01-01,NaT
1794,Competed in Olympic Games,Male,Luis•Castillo Sánchez,Luis•Castillo,"in Guayaquil, Guayas (ECU)",NaN,Ecuador,1801,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Luis Castillo,<NA>,<NA>,NaT,NaT
1800,Competed in Olympic Games,Male,Lincoln•Salcedo Reina,Lincoln•Salcedo,"in Guayaquil, Guayas (ECU)",NaN,Ecuador,1807,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Lincoln Salcedo,<NA>,<NA>,NaT,NaT
1805,Competed in Olympic Games,Male,Gharib Ibrahim•Afifi,Gharib•Afifi,"in Al-Qahira (Cairo), Al-Qahira (EGY)",(In the 1990s),Egypt,1812,NaN,"El-Olympi, Al-Iskanderiya (EGY)",...,NaN,NaN,NaN,غريب ابراهيم•عفيفي,NaN,Gharib Afifi,<NA>,<NA>,NaT,1990-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86829,Competed in Olympic Games,Male,Charles•Jenny,Charles•Jenny,"April 1897 in Basel, Basel-Stadt (SUI)",NaN,Switzerland,87523,178 cm,NaN,...,NaN,NaN,NaN,NaN,NaN,Charles Jenny,178,<NA>,1897-01-01,NaT
100003,Competed in Olympic Games,Male,Gora Chand•Seal,Gora•Seal,January 1923,"23 September 2017 in Kolkata (Calcutta), West ...",India,100829,NaN,"Central Swimming Club, Kolkata (IND)",...,NaN,NaN,NaN,NaN,NaN,Gora Seal,<NA>,<NA>,1923-01-01,2017-09-23
101533,Competed in Olympic Games,Male,David Hey•Bratton,David•Bratton,"October 1869 in New York, New York (USA)","3 December 1904 in Chicago, Illinois (USA)",United States,102423,NaN,"NYAC, New York (USA)",...,NaN,NaN,NaN,NaN,NaN,David Bratton,<NA>,<NA>,1869-01-01,1904-12-03
101534,Competed in Olympic Games,Male,David A.•Hesser,David•Hesser,"January 1884 in ?, New York (USA)","13 February 1908 in Manhattan, New York, New Y...",United States,102424,NaN,"NYAC, New York (USA)",...,NaN,NaN,NaN,NaN,NaN,David Hesser,<NA>,<NA>,1884-01-01,1908-02-13
116330,Competed in Olympic Games,Female,Cha•Yong-Hwa,Cha•Yong-Hwa,"in Pyeongyang, Pyeongyang (PRK)",NaN,Democratic People's Republic of Korea,117719,145 cm / 39 kg,Pyongyang Sports Club,...,NaN,NaN,NaN,NaN,Oriental,Cha Yong-Hwa,145,39,NaT,NaT

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   roles          145500 non-null  object
 1   sex            145500 non-null  object
 2   full_name      145500 non-null  object
 3   used_name      145500 non-null  object
 4   born           143772 non-null  object
 5   died           34042 non-null   object
 6   noc            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   measurements   107833 non-null  object
 9   affiliations   95832 non-null   object
 10  nick/petnames  9145 non-null    object
 11  title(s)       399 non-null     object
 12  other_names    7167 non-null    object
 13  nationality    8259 non-null    object
 14  original_name  30739 non-null   object
 15  name_order     7844 non-null    object
 16  name           145500 non-null  object
 17  height_cm      106651 non-null  Int64
 18  weight_kg      104210 non-null  Int64
 19  born_date      143698 non-null  datetime64[ns]
 20  date_died      33963 non-null   datetime64[ns]
dtypes: Int64(2), datetime64[ns](2), int64(1), object(16)
memory usage: 23.6+ MB

In [ ]:
#df['age_at_death1'] = (df['date_died'] - df['born_date'])/np.timedelta64(1,'Y')
df['age_at_death'] = ((df['date_died'] - df['born_date']).dt.days/360).round().astype('Int64')

In [ ]:
df.born_date[:2]

0   1886-12-12
1   1969-04-01
Name: born_date, dtype: datetime64[ns]

In [ ]:
df['date_died'][:2]

0   1960-10-02
1          NaT
Name: date_died, dtype: datetime64[ns]

In [ ]:
#df[['city','region','country',]] = df['born'].extract(r" in (\w+)")
#df[['city','region']] = df['born'].str.extract(r"in (\w+)\,+(\w+)")
df[['city', 'region', 'country']] = df['born'].str.extract(r'in\s+([^,]+),\s*([^(]+)\s*\(([^)]+)\)')

df.columns

Index(['roles', 'sex', 'full_name', 'used_name', 'born', 'died', 'noc',
       'athlete_id', 'measurements', 'affiliations', 'nick/petnames',
       'title(s)', 'other_names', 'nationality', 'original_name', 'name_order',
       'name', 'height_cm', 'weight_kg', 'born_date', 'date_died',
       'age_at_death', 'city', 'region', 'country'],
      dtype='object')

In [ ]:
data_cleaned = df.drop(columns = ['used_name', 'born','noc','athlete_id', 'measurements', 'affiliations', 'nick/petnames','title(s)', 'other_names', 'nationality', 'original_name', 'name_order','name'])
data_cleaned.head()

,roles,sex,full_name,died,height_cm,weight_kg,born_date,date_died,age_at_death,city,region,country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",<NA>,<NA>,1886-12-12,1960-10-02,75,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,NaN,183,76,1969-04-01,NaT,<NA>,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,"17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",183,76,1898-08-13,1994-07-17,97,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,"20 March 1978 in Monaco, Monaco (MON)",168,64,1895-05-11,1978-03-20,84,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,"25 July 1930 in Paris VIIe, Paris (FRA)",<NA>,<NA>,1878-04-17,1930-07-25,53,Wandsworth,England,GBR

In [ ]:
data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   roles         145500 non-null  object
 1   sex           145500 non-null  object
 2   full_name     145500 non-null  object
 3   died          34042 non-null   object
 4   height_cm     106651 non-null  Int64
 5   weight_kg     104210 non-null  Int64
 6   born_date     143698 non-null  datetime64[ns]
 7   date_died     33963 non-null   datetime64[ns]
 8   age_at_death  33872 non-null   Int64
 9   city          119398 non-null  object
 10  region        119398 non-null  object
 11  country       119398 non-null  object
dtypes: Int64(3), datetime64[ns](2), object(7)
memory usage: 13.7+ MB

In [ ]:
data_cleaned.to_csv('cleaned_athlete_data.csv.zip',index=False,compression='zip')
from google.colab import files
files.download('cleaned_athlete_data.csv.zip')