In [515]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [516]:
#. perform EDA
df = pd.read_excel(r"C:\Users\solomon\Desktop\employee.xlsx")

In [517]:
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date
0,101,Alice,25,HR,50000.0,2,New York,2022-01-15
1,102,Bob,NaN,IT,65000.0,5,Chicago,2020-06-10
2,103,Charlie,Thirty,Finance,72000.0,7,Houston,2018-09-20
3,104,David,29,IT,NaN,4,Chicago,2021-03-12
4,105,Eva,35,HR,58000.0,NaN,New York,2019-11-01

In [518]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  23 non-null     int64
 1   Name         23 non-null     object
 2   Age          21 non-null     object
 3   Department   23 non-null     object
 4   Salary       21 non-null     float64
 5   Experience   22 non-null     object
 6   City         21 non-null     object
 7   Join_Date    22 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 1.6+ KB

In [519]:
# calculate the percent of missing value for each columns
df.isna().sum()

Employee_ID    0
Name           0
Age            2
Department     0
Salary         2
Experience     1
City           2
Join_Date      1
dtype: int64

In [520]:
df['Age'] = pd.to_numeric(df['Age'],errors = 'coerce')
df['Experience'] = pd.to_numeric(df['Experience'],errors = 'coerce')

In [521]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  23 non-null     int64
 1   Name         23 non-null     object
 2   Age          17 non-null     float64
 3   Department   23 non-null     object
 4   Salary       21 non-null     float64
 5   Experience   21 non-null     float64
 6   City         21 non-null     object
 7   Join_Date    22 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.6+ KB

In [522]:
#3  Fill missing ages with the median age. 
df['Age'] = df['Age'].fillna(df['Age'].median())

In [523]:
#4  Fill missing salaries with the average salary. 
df['Salary'] = df['Salary'].fillna(df['Salary'].mean()).round(1)

In [524]:
#5  Fill missing cities with "Unknown".
df['City'] = df['City'].fillna('Unknown')

In [525]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],errors = 'coerce')

In [526]:
#6  Convert Join_Date to datetime.
df['Join_Date'].dtype

dtype('<M8[ns]')

In [527]:
# Check whether there are any duplicates and remove them
df.loc[df.duplicated()]

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date
20,120,Tom,29.0,IT,61000.0,2.0,Chicago,2023-03-15
21,113,Mary,28.0,IT,62000.0,3.0,Chicago,2022-05-10
22,106,Frank,40.0,Finance,85000.0,10.0,Unknown,2015-08-15

In [528]:
df = df.drop_duplicates()

In [529]:
# Check whether there are any duplicates.
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Department, Salary, Experience, City, Join_Date]
Index: []

In [530]:
#Count employees in each city.
df.City.value_counts()

City
Chicago     8
New York    6
Houston     5
Unknown     1
Name: count, dtype: int64

In [531]:
#Find the average experience by department.
df.groupby('Department').Experience.mean()

Department
Finance    7.333333
HR         6.400000
IT         4.428571
Name: Experience, dtype: float64

In [532]:
# Create a column called Bonus equal to 10% of salary.
df['bonus'] = (df['Salary']*0.1).round(1)

In [533]:
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus
0,101,Alice,25.0,HR,50000.0,2.0,New York,2022-01-15,5000.0
1,102,Bob,29.0,IT,65000.0,5.0,Chicago,2020-06-10,6500.0
2,103,Charlie,29.0,Finance,72000.0,7.0,Houston,2018-09-20,7200.0
3,104,David,29.0,IT,68333.3,4.0,Chicago,2021-03-12,6833.3
4,105,Eva,35.0,HR,58000.0,NaN,New York,2019-11-01,5800.0

In [534]:
# Create a column senior with  a label yes and no
df['Senior'] = np.where(df['Experience'] >=5,'Yes','No')

In [535]:
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus,Senior
0,101,Alice,25.0,HR,50000.0,2.0,New York,2022-01-15,5000.0,No
1,102,Bob,29.0,IT,65000.0,5.0,Chicago,2020-06-10,6500.0,Yes
2,103,Charlie,29.0,Finance,72000.0,7.0,Houston,2018-09-20,7200.0,Yes
3,104,David,29.0,IT,68333.3,4.0,Chicago,2021-03-12,6833.3,No
4,105,Eva,35.0,HR,58000.0,NaN,New York,2019-11-01,5800.0,No

In [536]:
df['Year'] = df.Join_Date.dt.year

In [537]:
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus,Senior,Year
0,101,Alice,25.0,HR,50000.0,2.0,New York,2022-01-15,5000.0,No,2022.0
1,102,Bob,29.0,IT,65000.0,5.0,Chicago,2020-06-10,6500.0,Yes,2020.0
2,103,Charlie,29.0,Finance,72000.0,7.0,Houston,2018-09-20,7200.0,Yes,2018.0
3,104,David,29.0,IT,68333.3,4.0,Chicago,2021-03-12,6833.3,No,2021.0
4,105,Eva,35.0,HR,58000.0,NaN,New York,2019-11-01,5800.0,No,2019.0

In [538]:
# Find employees who joined after 2020.
df[df.Year > 2020]

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus,Senior,Year
0,101,Alice,25.0,HR,50000.0,2.0,New York,2022-01-15,5000.0,No,2022.0
3,104,David,29.0,IT,68333.3,4.0,Chicago,2021-03-12,6833.3,No,2021.0
6,107,Grace,27.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
12,113,Mary,28.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
14,115,Oscar,29.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
15,116,Paul,29.0,HR,54000.0,2.0,New York,2023-01-10,5400.0,No,2023.0
18,119,Sarah,27.0,HR,58000.0,4.0,New York,2021-09-01,5800.0,No,2021.0
19,120,Tom,29.0,IT,61000.0,2.0,Chicago,2023-03-15,6100.0,No,2023.0

In [539]:
#Find the top 5 highest-paid employees.
df.sort_values(by = 'Salary',ascending=False).head(5)

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus,Senior,Year
11,112,Luke,45.0,HR,91000.0,20.0,New York,2010-04-05,9100.0,Yes,2010.0
17,118,Ryan,41.0,IT,87000.0,11.0,Chicago,2014-06-30,8700.0,Yes,2014.0
5,106,Frank,40.0,Finance,85000.0,10.0,Unknown,2015-08-15,8500.0,Yes,2015.0
9,110,Jack,31.0,Finance,85000.0,6.0,Houston,2019-02-18,8500.0,Yes,2019.0
16,117,Queen,34.0,Finance,78000.0,8.0,Houston,2017-12-25,7800.0,Yes,2017.0

In [540]:
#Find employees whose names start with "A"
df[df.Name.str.startswith('A',na=False)]

,Employee_ID,Name,Age,Department,Salary,Experience,City,Join_Date,bonus,Senior,Year
0,101,Alice,25.0,HR,50000.0,2.0,New York,2022-01-15,5000.0,No,2022.0

In [550]:
# Find employees whose names contain the letter "a"
df[df.Name.str.contains('a')]

,Employee_Id,Name,Age,Department,Salary,Experience,City,Join_Date,Bonus,Senior,Year
2,103,Charlie,29.0,Finance,72000.0,7.0,Houston,2018-09-20,7200.0,Yes,2018.0
3,104,David,29.0,IT,68333.3,4.0,Chicago,2021-03-12,6833.3,No,2021.0
4,105,Eva,35.0,HR,58000.0,NaN,New York,2019-11-01,5800.0,No,2019.0
5,106,Frank,40.0,Finance,85000.0,10.0,Unknown,2015-08-15,8500.0,Yes,2015.0
6,107,Grace,27.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
8,109,Ian,31.0,Finance,68333.3,6.0,Houston,2019-02-18,6833.3,Yes,2019.0
9,110,Jack,31.0,Finance,85000.0,6.0,Houston,2019-02-18,8500.0,Yes,2019.0
10,111,Kate,29.0,IT,67000.0,NaN,Chicago,2020-07-15,6700.0,No,2020.0
12,113,Mary,28.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
13,114,Nina,29.0,Finance,72000.0,7.0,Houston,2018-09-20,7200.0,Yes,2018.0
14,115,Oscar,29.0,IT,62000.0,3.0,Chicago,2022-05-10,6200.0,No,2022.0
15,116,Paul,29.0,HR,54000.0,2.0,New York,2023-01-10,5400.0,No,2023.0
17,118,Ryan,41.0,IT,87000.0,11.0,Chicago,2014-06-30,8700.0,Yes,2014.0
18,119,Sarah,27.0,HR,58000.0,4.0,New York,2021-09-01,5800.0,No,2021.0

In [551]:
(df.isna().sum()/len(df)*100)*round(2)

Employee_Id     0.0
Name            0.0
Age             0.0
Department      0.0
Salary          0.0
Experience     20.0
City            0.0
Join_Date      10.0
Bonus           0.0
Senior          0.0
Year           10.0
dtype: float64

In [569]:
df.loc[df['Experience'].idxmax(),'Name']

'Luke'

In [570]:
# Find the employee with the most experience.
df.sort_values('Experience',ascending = False).head(1)

,Employee_Id,Name,Age,Department,Salary,Experience,City,Join_Date,Bonus,Senior,Year
11,112,Luke,45.0,HR,91000.0,20.0,New York,2010-04-05,9100.0,Yes,2010.0

In [572]:
# Produce a summary report showing:
df1 = df.agg(number_of_employee = ('Name','count'),
                             average_salary = ('Salary','mean'),
                             average_age = ('Age','mean'),
                             highest_salary = ('Salary','max'),
                             city_highemployee = ('City','count')
       
                            ).round(1)

In [583]:
pd.DataFrame({'metrics':['number_of_employee','average_salary','average_age','high_pay_dep','city_highemployee'],
                   'Value':[df.Name.count(),df.Salary.mean(),df.Age.mean(),df.groupby('Department').Salary.mean().idxmax(),df.City.value_counts().idxmax()]
                   })

              metrics     Value
0  number_of_employee        20
1      average_salary  68183.33
2         average_age     31.25
3        high_pay_dep   Finance
4   city_highemployee   Chicago

In [586]:
df.groupby('Department').Salary.mean()

Department
Finance    76722.216667
HR         61500.000000
IT         66791.662500
Name: Salary, dtype: float64